# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: DigitalRats
email: moyshe@digitalrats.ru
description: >- # this means to ignore newlines until "baseurl:"
  DigitalRats studio was founden in a memories of older team CRG. 
  It was a late 90s Sinclair ZX-SPECTRUM fan group im my own city.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://digitalrats.ru" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: digitalrats
github_username:  digitalrats

# Build settings
lsi: false
safe: true
#source: https://github.com/digitalrats/digitalrats.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: minima

localization:
  mode: manual
  locale: ru-RU
  locales_set: 
    ru-RU:
      lable: Russian
      dir: ltr
    en-US:
      label: English
      dir: ltr

exclude:
  - Gemfile
  - Gemfile.lock
  - postcss.config.js

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
